//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cielo.Sirius.DAO.Products.MaterialService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/operacao/logistica/v1")]
    public partial class Material : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMaterialField;
        
        private string descricaoMaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
                this.RaisePropertyChanged("codigoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string descricaoMaterial {
            get {
                return this.descricaoMaterialField;
            }
            set {
                this.descricaoMaterialField = value;
                this.RaisePropertyChanged("descricaoMaterial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/operacao/logistica/v1")]
    public partial class MaterialSolicitadoCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private Material dadosMaterialField;
        
        private string quantidadeMaterialField;
        
        private string quantidadeDiaPrazoEntregaField;
        
        private System.Nullable<System.DateTime> dataSolicitacaoField;
        
        private bool dataSolicitacaoFieldSpecified;
        
        private string codigoUsuarioOperadorField;
        
        private string nomeTipoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
                this.RaisePropertyChanged("codigoClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Material dadosMaterial {
            get {
                return this.dadosMaterialField;
            }
            set {
                this.dadosMaterialField = value;
                this.RaisePropertyChanged("dadosMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string quantidadeMaterial {
            get {
                return this.quantidadeMaterialField;
            }
            set {
                this.quantidadeMaterialField = value;
                this.RaisePropertyChanged("quantidadeMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=3)]
        public string quantidadeDiaPrazoEntrega {
            get {
                return this.quantidadeDiaPrazoEntregaField;
            }
            set {
                this.quantidadeDiaPrazoEntregaField = value;
                this.RaisePropertyChanged("quantidadeDiaPrazoEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dataSolicitacao {
            get {
                return this.dataSolicitacaoField;
            }
            set {
                this.dataSolicitacaoField = value;
                this.RaisePropertyChanged("dataSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSolicitacaoSpecified {
            get {
                return this.dataSolicitacaoFieldSpecified;
            }
            set {
                this.dataSolicitacaoFieldSpecified = value;
                this.RaisePropertyChanged("dataSolicitacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string codigoUsuarioOperador {
            get {
                return this.codigoUsuarioOperadorField;
            }
            set {
                this.codigoUsuarioOperadorField = value;
                this.RaisePropertyChanged("codigoUsuarioOperador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string nomeTipoSolicitacao {
            get {
                return this.nomeTipoSolicitacaoField;
            }
            set {
                this.nomeTipoSolicitacaoField = value;
                this.RaisePropertyChanged("nomeTipoSolicitacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", ConfigurationName="MaterialService.MaterialServicePortType")]
    internal interface MaterialServicePortType {
        
        // CODEGEN: Generating message contract since the operation consultarHistoricoSolicitacao is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.MaterialService.Fault), Action="", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoResponse consultarHistoricoSolicitacao(Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation consultarSuprimentoElegivel is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.MaterialService.Fault), Action="", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelResponse consultarSuprimentoElegivel(Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest1 request);
        
        // CODEGEN: Generating message contract since the operation consultarHistoricoConsumo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.MaterialService.Fault), Action="", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoResponse consultarHistoricoConsumo(Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation solicitarMaterial is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.MaterialService.Fault), Action="", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialResponse solicitarMaterial(Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class consultarHistoricoSolicitacaoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarHistoricoSolicitacaoRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        public Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest consultarHistoricoSolicitacaoRequest;
        
        public consultarHistoricoSolicitacaoRequest1() {
        }
        
        public consultarHistoricoSolicitacaoRequest1(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest consultarHistoricoSolicitacaoRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarHistoricoSolicitacaoRequest = consultarHistoricoSolicitacaoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarHistoricoSolicitacaoResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", IsWrapped=true)]
    internal partial class consultarHistoricoSolicitacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("materialSolicitadoCliente", IsNullable=false)]
        public Cielo.Sirius.DAO.Products.MaterialService.MaterialSolicitadoCliente[] materialSolicitadoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarHistoricoSolicitacaoResponse() {
        }
        
        public consultarHistoricoSolicitacaoResponse(Cielo.Sirius.DAO.Products.MaterialService.MaterialSolicitadoCliente[] materialSolicitadoCliente, string proximoRegistro, string chavePaginacao) {
            this.materialSolicitadoCliente = materialSolicitadoCliente;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class consultarSuprimentoElegivelRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarSuprimentoElegivelRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        public Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest consultarSuprimentoElegivelRequest;
        
        public consultarSuprimentoElegivelRequest1() {
        }
        
        public consultarSuprimentoElegivelRequest1(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest consultarSuprimentoElegivelRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarSuprimentoElegivelRequest = consultarSuprimentoElegivelRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSuprimentoElegivelResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", IsWrapped=true)]
    internal partial class consultarSuprimentoElegivelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("material", IsNullable=false)]
        public Cielo.Sirius.DAO.Products.MaterialService.Material[] materiais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarSuprimentoElegivelResponse() {
        }
        
        public consultarSuprimentoElegivelResponse(Cielo.Sirius.DAO.Products.MaterialService.Material[] materiais, string proximoRegistro, string chavePaginacao) {
            this.materiais = materiais;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class consultarHistoricoConsumoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string codigoMaterialField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
                this.RaisePropertyChanged("codigoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class InfoHistoricoConsumoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mesConsumoField;
        
        private string quantidadeSuprimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mesConsumo {
            get {
                return this.mesConsumoField;
            }
            set {
                this.mesConsumoField = value;
                this.RaisePropertyChanged("mesConsumo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string quantidadeSuprimento {
            get {
                return this.quantidadeSuprimentoField;
            }
            set {
                this.quantidadeSuprimentoField = value;
                this.RaisePropertyChanged("quantidadeSuprimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarHistoricoConsumoRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        public Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest consultarHistoricoConsumoRequest;
        
        public consultarHistoricoConsumoRequest1() {
        }
        
        public consultarHistoricoConsumoRequest1(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest consultarHistoricoConsumoRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarHistoricoConsumoRequest = consultarHistoricoConsumoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarHistoricoConsumoResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", IsWrapped=true)]
    internal partial class consultarHistoricoConsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        public Cielo.Sirius.DAO.Products.MaterialService.Material material;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("infoHistoricoConsumo", IsNullable=false)]
        public Cielo.Sirius.DAO.Products.MaterialService.InfoHistoricoConsumoType[] dadosHistoricoConsumo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarHistoricoConsumoResponse() {
        }
        
        public consultarHistoricoConsumoResponse(Cielo.Sirius.DAO.Products.MaterialService.Material material, Cielo.Sirius.DAO.Products.MaterialService.InfoHistoricoConsumoType[] dadosHistoricoConsumo, string proximoRegistro, string chavePaginacao) {
            this.material = material;
            this.dadosHistoricoConsumo = dadosHistoricoConsumo;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class solicitarMaterialRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protocoloField;
        
        private System.Nullable<long> codigoClienteField;
        
        private string codigoMaterialField;
        
        private string quantidadeMaterialField;
        
        private string nomeResponsavelField;
        
        private string nomeContatoField;
        
        private string telefoneContatoField;
        
        private string justificativaSolicitacaoField;
        
        private string codigoRacfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
                this.RaisePropertyChanged("codigoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=3)]
        public string quantidadeMaterial {
            get {
                return this.quantidadeMaterialField;
            }
            set {
                this.quantidadeMaterialField = value;
                this.RaisePropertyChanged("quantidadeMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nomeResponsavel {
            get {
                return this.nomeResponsavelField;
            }
            set {
                this.nomeResponsavelField = value;
                this.RaisePropertyChanged("nomeResponsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string nomeContato {
            get {
                return this.nomeContatoField;
            }
            set {
                this.nomeContatoField = value;
                this.RaisePropertyChanged("nomeContato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string telefoneContato {
            get {
                return this.telefoneContatoField;
            }
            set {
                this.telefoneContatoField = value;
                this.RaisePropertyChanged("telefoneContato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string justificativaSolicitacao {
            get {
                return this.justificativaSolicitacaoField;
            }
            set {
                this.justificativaSolicitacaoField = value;
                this.RaisePropertyChanged("justificativaSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string codigoRacf {
            get {
                return this.codigoRacfField;
            }
            set {
                this.codigoRacfField = value;
                this.RaisePropertyChanged("codigoRacf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/canalrelacionamento/atendimentoassistido/v1")]
    public partial class SolicitacaoCentralAtendimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private string codigoSolicitacaoField;
        
        private System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacaoField;
        
        private bool dataPrevistaConclusaoSolicitacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
                this.RaisePropertyChanged("codigoClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string codigoSolicitacao {
            get {
                return this.codigoSolicitacaoField;
            }
            set {
                this.codigoSolicitacaoField = value;
                this.RaisePropertyChanged("codigoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacao {
            get {
                return this.dataPrevistaConclusaoSolicitacaoField;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoField = value;
                this.RaisePropertyChanged("dataPrevistaConclusaoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPrevistaConclusaoSolicitacaoSpecified {
            get {
                return this.dataPrevistaConclusaoSolicitacaoFieldSpecified;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoFieldSpecified = value;
                this.RaisePropertyChanged("dataPrevistaConclusaoSolicitacaoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class solicitarMaterialRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        public Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest solicitarMaterialRequest;
        
        public solicitarMaterialRequest1() {
        }
        
        public solicitarMaterialRequest1(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest solicitarMaterialRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.solicitarMaterialRequest = solicitarMaterialRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarMaterialResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", IsWrapped=true)]
    internal partial class solicitarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=1)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=2)]
        public string statusRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=3)]
        public string sistemaLegado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Order=4)]
        public Cielo.Sirius.DAO.Products.MaterialService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento;
        
        public solicitarMaterialResponse() {
        }
        
        public solicitarMaterialResponse(string codigoRetorno, string descricaoRetornoMensagem, string statusRetorno, string sistemaLegado, Cielo.Sirius.DAO.Products.MaterialService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.statusRetorno = statusRetorno;
            this.sistemaLegado = sistemaLegado;
            this.solicitacaoCentralAtendimento = solicitacaoCentralAtendimento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface MaterialServicePortTypeChannel : Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MaterialServicePortTypeClient : System.ServiceModel.ClientBase<Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType>, Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType {
        
        public MaterialServicePortTypeClient() {
        }
        
        public MaterialServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoResponse Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType.consultarHistoricoSolicitacao(Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest1 request) {
            return base.Channel.consultarHistoricoSolicitacao(request);
        }
        
        public Cielo.Sirius.DAO.Products.MaterialService.MaterialSolicitadoCliente[] consultarHistoricoSolicitacao(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest consultarHistoricoSolicitacaoRequest, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest1 inValue = new Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarHistoricoSolicitacaoRequest = consultarHistoricoSolicitacaoRequest;
            Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoSolicitacaoResponse retVal = ((Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType)(this)).consultarHistoricoSolicitacao(inValue);
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.materialSolicitadoCliente;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelResponse Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType.consultarSuprimentoElegivel(Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest1 request) {
            return base.Channel.consultarSuprimentoElegivel(request);
        }
        
        public Cielo.Sirius.DAO.Products.MaterialService.Material[] consultarSuprimentoElegivel(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest consultarSuprimentoElegivelRequest, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest1 inValue = new Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarSuprimentoElegivelRequest = consultarSuprimentoElegivelRequest;
            Cielo.Sirius.DAO.Products.MaterialService.consultarSuprimentoElegivelResponse retVal = ((Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType)(this)).consultarSuprimentoElegivel(inValue);
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.materiais;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoResponse Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType.consultarHistoricoConsumo(Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest1 request) {
            return base.Channel.consultarHistoricoConsumo(request);
        }
        
        public Cielo.Sirius.DAO.Products.MaterialService.Material consultarHistoricoConsumo(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest consultarHistoricoConsumoRequest, out Cielo.Sirius.DAO.Products.MaterialService.InfoHistoricoConsumoType[] dadosHistoricoConsumo, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest1 inValue = new Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarHistoricoConsumoRequest = consultarHistoricoConsumoRequest;
            Cielo.Sirius.DAO.Products.MaterialService.consultarHistoricoConsumoResponse retVal = ((Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType)(this)).consultarHistoricoConsumo(inValue);
            dadosHistoricoConsumo = retVal.dadosHistoricoConsumo;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.material;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialResponse Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType.solicitarMaterial(Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest1 request) {
            return base.Channel.solicitarMaterial(request);
        }
        
        public string solicitarMaterial(Cielo.Sirius.DAO.Products.MaterialService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest solicitarMaterialRequest, out string descricaoRetornoMensagem, out string statusRetorno, out string sistemaLegado, out Cielo.Sirius.DAO.Products.MaterialService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest1 inValue = new Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.solicitarMaterialRequest = solicitarMaterialRequest;
            Cielo.Sirius.DAO.Products.MaterialService.solicitarMaterialResponse retVal = ((Cielo.Sirius.DAO.Products.MaterialService.MaterialServicePortType)(this)).solicitarMaterial(inValue);
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            statusRetorno = retVal.statusRetorno;
            sistemaLegado = retVal.sistemaLegado;
            solicitacaoCentralAtendimento = retVal.solicitacaoCentralAtendimento;
            return retVal.codigoRetorno;
        }
    }
}
