//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cielo.Sirius.DAO.Products.UnitTest.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IProdutosService")]
    public interface IProdutosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarInformacoesPatAleloCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarInformacoesPatAleloClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloResponse ConsultarInformacoesPatAleloCliente(Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarInformacoesPatAleloCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarInformacoesPatAleloClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloResponse> ConsultarInformacoesPatAleloClienteAsync(Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoHabilitadoClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteResponse ConsultarProdutoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoHabilitadoClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteResponse> ConsultarProdutoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoHabilitadoClienteRespo" +
            "nse")]
        Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteResponse ConsultarDetalheProdutoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoHabilitadoClienteRespo" +
            "nse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteResponse> ConsultarDetalheProdutoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoElegivelClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteResponse ConsultarProdutoElegivelCliente(Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoElegivelClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteResponse> ConsultarProdutoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoElegivelClienteRespons" +
            "e")]
        Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteResponse ConsultarDetalheProdutoElegivelCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoElegivelClienteRespons" +
            "e")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteResponse> ConsultarDetalheProdutoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoNaoElegivelClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteResponse ConsultarProdutoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutoNaoElegivelClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteResponse> ConsultarProdutoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoNaoElegivelClienteResp" +
            "onse")]
        Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteResponse ConsultarDetalheProdutoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoNaoElegivelClienteResp" +
            "onse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteResponse> ConsultarDetalheProdutoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestsHistory", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestsHistoryResponse")]
        Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryResponse GetProductRequestsHistory(Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestsHistory", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestsHistoryResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryResponse> GetProductRequestsHistoryAsync(Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestsHistory", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestsHistoryResponse")]
        Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryResponse GetServiceRequestsHistory(Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestsHistory", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestsHistoryResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryResponse> GetServiceRequestsHistoryAsync(Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesEnabledResponse")]
        Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesResponse GetProductRequestTypesEnabled(Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesEnabledResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesResponse> GetProductRequestTypesEnabledAsync(Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesEnabledResponse")]
        Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesResponse GetServiceRequestTypesEnabled(Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesEnabledResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesResponse> GetServiceRequestTypesEnabledAsync(Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonEnabledResponse")]
        Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesResponse GetServiceRequestTypesNonEnabled(Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonEnabledResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesResponse> GetServiceRequestTypesNonEnabledAsync(Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonElegible", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonElegibleResponse")]
        Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesResponse GetServiceRequestTypesNonElegible(Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonElegible", ReplyAction="http://tempuri.org/IProdutosService/GetServiceRequestTypesNonElegibleResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesResponse> GetServiceRequestTypesNonElegibleAsync(Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEligible", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEligibleResponse")]
        Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesResponse GetProductRequestTypesNonEligible(Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEligible", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEligibleResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesResponse> GetProductRequestTypesNonEligibleAsync(Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEnabledResponse")]
        Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesResponse GetProductRequestTypesNonEnabled(Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEnabled", ReplyAction="http://tempuri.org/IProdutosService/GetProductRequestTypesNonEnabledResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesResponse> GetProductRequestTypesNonEnabledAsync(Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarPrazoPadrao", ReplyAction="http://tempuri.org/IProdutosService/ConsultarPrazoPadraoResponse")]
        Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoResponse ConsultarPrazoPadrao(Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarPrazoPadrao", ReplyAction="http://tempuri.org/IProdutosService/ConsultarPrazoPadraoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoResponse> ConsultarPrazoPadraoAsync(Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarTaxa", ReplyAction="http://tempuri.org/IProdutosService/AlterarTaxaResponse")]
        Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoResponse AlterarTaxa(Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarTaxa", ReplyAction="http://tempuri.org/IProdutosService/AlterarTaxaResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoResponse> AlterarTaxaAsync(Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitarNegociacaoTaxaProdutoComercial", ReplyAction="http://tempuri.org/IProdutosService/SolicitarNegociacaoTaxaProdutoComercialRespon" +
            "se")]
        Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaResponse SolicitarNegociacaoTaxaProdutoComercial(Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitarNegociacaoTaxaProdutoComercial", ReplyAction="http://tempuri.org/IProdutosService/SolicitarNegociacaoTaxaProdutoComercialRespon" +
            "se")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaResponse> SolicitarNegociacaoTaxaProdutoComercialAsync(Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetDiscountRateRestriction", ReplyAction="http://tempuri.org/IProdutosService/GetDiscountRateRestrictionResponse")]
        Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionResponse GetDiscountRateRestriction(Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetDiscountRateRestriction", ReplyAction="http://tempuri.org/IProdutosService/GetDiscountRateRestrictionResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionResponse> GetDiscountRateRestrictionAsync(Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ManterPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ManterPrazoFlexivelResponse")]
        Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelResponse ManterPrazoFlexivel(Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ManterPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ManterPrazoFlexivelResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelResponse> ManterPrazoFlexivelAsync(Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarDesabilitarVendaDigitada", ReplyAction="http://tempuri.org/IProdutosService/HabilitarDesabilitarVendaDigitadaResponse")]
        Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaResponse HabilitarDesabilitarVendaDigitada(Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarDesabilitarVendaDigitada", ReplyAction="http://tempuri.org/IProdutosService/HabilitarDesabilitarVendaDigitadaResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaResponse> HabilitarDesabilitarVendaDigitadaAsync(Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitarExclusaoProduto", ReplyAction="http://tempuri.org/IProdutosService/SolicitarExclusaoProdutoResponse")]
        Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoResponse SolicitarExclusaoProduto(Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitarExclusaoProduto", ReplyAction="http://tempuri.org/IProdutosService/SolicitarExclusaoProdutoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoResponse> SolicitarExclusaoProdutoAsync(Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoHabilitadoClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteResponse ConsultarServicoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoHabilitadoCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoHabilitadoClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteResponse> ConsultarServicoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoMultivanContratadoClie" +
            "nte", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoMultivanContratadoClie" +
            "nteResponse")]
        Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteResponse ConsultarDetalheProdutoMultivanContratadoCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoMultivanContratadoClie" +
            "nte", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDetalheProdutoMultivanContratadoClie" +
            "nteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteResponse> ConsultarDetalheProdutoMultivanContratadoClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitaAnaliseAlvara", ReplyAction="http://tempuri.org/IProdutosService/SolicitaAnaliseAlvaraResponse")]
        Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraResponse SolicitaAnaliseAlvara(Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/SolicitaAnaliseAlvara", ReplyAction="http://tempuri.org/IProdutosService/SolicitaAnaliseAlvaraResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraResponse> SolicitaAnaliseAlvaraAsync(Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarProduto", ReplyAction="http://tempuri.org/IProdutosService/HabilitarProdutoResponse")]
        Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoResponse HabilitarProduto(Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarProduto", ReplyAction="http://tempuri.org/IProdutosService/HabilitarProdutoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoResponse> HabilitarProdutoAsync(Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoElegivelClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteResponse ConsultarServicoElegivelCliente(Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoElegivelClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteResponse> ConsultarServicoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoNaoElegivelClienteResponse")]
        Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteResponse ConsultarServicoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarServicoNaoElegivelCliente", ReplyAction="http://tempuri.org/IProdutosService/ConsultarServicoNaoElegivelClienteResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteResponse> ConsultarServicoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ValidarPermissaoVendaDigitiada", ReplyAction="http://tempuri.org/IProdutosService/ValidarPermissaoVendaDigitiadaResponse")]
        Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaResponse ValidarPermissaoVendaDigitiada(Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ValidarPermissaoVendaDigitiada", ReplyAction="http://tempuri.org/IProdutosService/ValidarPermissaoVendaDigitiadaResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaResponse> ValidarPermissaoVendaDigitiadaAsync(Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarServico", ReplyAction="http://tempuri.org/IProdutosService/HabilitarServicoResponse")]
        Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoResponse HabilitarServico(Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/HabilitarServico", ReplyAction="http://tempuri.org/IProdutosService/HabilitarServicoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoResponse> HabilitarServicoAsync(Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/DesabilitarServico", ReplyAction="http://tempuri.org/IProdutosService/DesabilitarServicoResponse")]
        Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoResponse DesabilitarServico(Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/DesabilitarServico", ReplyAction="http://tempuri.org/IProdutosService/DesabilitarServicoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoResponse> DesabilitarServicoAsync(Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/DesabilitarProduto", ReplyAction="http://tempuri.org/IProdutosService/DesabilitarProdutoResponse")]
        Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoResponse DesabilitarProduto(Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/DesabilitarProduto", ReplyAction="http://tempuri.org/IProdutosService/DesabilitarProdutoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoResponse> DesabilitarProdutoAsync(Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarPrazosTaxasPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ConsultarPrazosTaxasPrazoFlexivelResponse")]
        Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelResponse ConsultarPrazosTaxasPrazoFlexivel(Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarPrazosTaxasPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ConsultarPrazosTaxasPrazoFlexivelResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelResponse> ConsultarPrazosTaxasPrazoFlexivelAsync(Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutosPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutosPrazoFlexivelResponse")]
        Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelResponse ConsultarProdutosPrazoFlexivel(Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarProdutosPrazoFlexivel", ReplyAction="http://tempuri.org/IProdutosService/ConsultarProdutosPrazoFlexivelResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelResponse> ConsultarProdutosPrazoFlexivelAsync(Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetRequestReason", ReplyAction="http://tempuri.org/IProdutosService/GetRequestReasonResponse")]
        Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonResponse GetRequestReason(Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/GetRequestReason", ReplyAction="http://tempuri.org/IProdutosService/GetRequestReasonResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonResponse> GetRequestReasonAsync(Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoSegmentado", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoSegmentadoRespo" +
            "nse")]
        Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoResponse AlterarProdutoCreditoParceladoSegmentado(Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoSegmentado", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoSegmentadoRespo" +
            "nse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoResponse> AlterarProdutoCreditoParceladoSegmentadoAsync(Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoAVista", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoAVistaResponse")]
        Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaResponse AlterarProdutoAVista(Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoAVista", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoAVistaResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaResponse> AlterarProdutoAVistaAsync(Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/CalcularAlcadaFaixasParceladoSegmentado", ReplyAction="http://tempuri.org/IProdutosService/CalcularAlcadaFaixasParceladoSegmentadoRespon" +
            "se")]
        Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoResponse CalcularAlcadaFaixasParceladoSegmentado(Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/CalcularAlcadaFaixasParceladoSegmentado", ReplyAction="http://tempuri.org/IProdutosService/CalcularAlcadaFaixasParceladoSegmentadoRespon" +
            "se")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoResponse> CalcularAlcadaFaixasParceladoSegmentadoAsync(Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParcelado", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoResponse")]
        Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoResponse AlterarProdutoCreditoParcelado(Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParcelado", ReplyAction="http://tempuri.org/IProdutosService/AlterarProdutoCreditoParceladoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoResponse> AlterarProdutoCreditoParceladoAsync(Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDadosNegociacao", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDadosNegociacaoResponse")]
        Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoResponse ConsultarDadosNegociacao(Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoRequest requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosService/ConsultarDadosNegociacao", ReplyAction="http://tempuri.org/IProdutosService/ConsultarDadosNegociacaoResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoResponse> ConsultarDadosNegociacaoAsync(Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoRequest requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutosServiceChannel : Cielo.Sirius.DAO.Products.UnitTest.Proxy.IProdutosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosServiceClient : System.ServiceModel.ClientBase<Cielo.Sirius.DAO.Products.UnitTest.Proxy.IProdutosService>, Cielo.Sirius.DAO.Products.UnitTest.Proxy.IProdutosService {
        
        public ProdutosServiceClient() {
        }
        
        public ProdutosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloResponse ConsultarInformacoesPatAleloCliente(Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloRequest requestData) {
            return base.Channel.ConsultarInformacoesPatAleloCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloResponse> ConsultarInformacoesPatAleloClienteAsync(Cielo.Sirius.Contracts.ConsultarInformacoesPatAlelo.ConsultarInformacoesPatAleloRequest requestData) {
            return base.Channel.ConsultarInformacoesPatAleloClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteResponse ConsultarProdutoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarProdutoHabilitadoCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteResponse> ConsultarProdutoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoHabilitadoCliente.ConsultarProdutoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarProdutoHabilitadoClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteResponse ConsultarDetalheProdutoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoHabilitadoCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteResponse> ConsultarDetalheProdutoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoHabilitadoCliente.ConsultarDetalheProdutoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoHabilitadoClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteResponse ConsultarProdutoElegivelCliente(Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarProdutoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteResponse> ConsultarProdutoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoElegivelCliente.ConsultarProdutoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarProdutoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteResponse ConsultarDetalheProdutoElegivelCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteResponse> ConsultarDetalheProdutoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoElegivelCliente.ConsultarDetalheProdutoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteResponse ConsultarProdutoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarProdutoNaoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteResponse> ConsultarProdutoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarProdutoNaoElegivelCliente.ConsultarProdutoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarProdutoNaoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteResponse ConsultarDetalheProdutoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoNaoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteResponse> ConsultarDetalheProdutoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoNaoElegivelCliente.ConsultarDetalheProdutoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoNaoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryResponse GetProductRequestsHistory(Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryRequest requestData) {
            return base.Channel.GetProductRequestsHistory(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryResponse> GetProductRequestsHistoryAsync(Cielo.Sirius.Contracts.GetProductRequestsHistory.GetProductRequestsHistoryRequest requestData) {
            return base.Channel.GetProductRequestsHistoryAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryResponse GetServiceRequestsHistory(Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryRequest requestData) {
            return base.Channel.GetServiceRequestsHistory(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryResponse> GetServiceRequestsHistoryAsync(Cielo.Sirius.Contracts.GetServiceRequestsHistory.GetServiceRequestsHistoryRequest requestData) {
            return base.Channel.GetServiceRequestsHistoryAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesResponse GetProductRequestTypesEnabled(Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesEnabled(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesResponse> GetProductRequestTypesEnabledAsync(Cielo.Sirius.Contracts.GetEnabledProductRequestTypes.GetEnabledProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesEnabledAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesResponse GetServiceRequestTypesEnabled(Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesEnabled(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesResponse> GetServiceRequestTypesEnabledAsync(Cielo.Sirius.Contracts.GetEnabledServiceRequestTypes.GetEnabledServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesEnabledAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesResponse GetServiceRequestTypesNonEnabled(Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesNonEnabled(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesResponse> GetServiceRequestTypesNonEnabledAsync(Cielo.Sirius.Contracts.Products.GetNonEnabledServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesNonEnabledAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesResponse GetServiceRequestTypesNonElegible(Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesNonElegible(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesResponse> GetServiceRequestTypesNonElegibleAsync(Cielo.Sirius.Contracts.Products.GetNonEligibleServiceRequestTypesRequest requestData) {
            return base.Channel.GetServiceRequestTypesNonElegibleAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesResponse GetProductRequestTypesNonEligible(Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesNonEligible(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesResponse> GetProductRequestTypesNonEligibleAsync(Cielo.Sirius.Contracts.GetNonEligibleProductRequestTypes.GetNonEligibleProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesNonEligibleAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesResponse GetProductRequestTypesNonEnabled(Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesNonEnabled(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesResponse> GetProductRequestTypesNonEnabledAsync(Cielo.Sirius.Contracts.GetNonEnabledProductRequestTypes.GetNonEnabledProductRequestTypesRequest requestData) {
            return base.Channel.GetProductRequestTypesNonEnabledAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoResponse ConsultarPrazoPadrao(Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoRequest requestData) {
            return base.Channel.ConsultarPrazoPadrao(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoResponse> ConsultarPrazoPadraoAsync(Cielo.Sirius.Contracts.ConsultarPrazoPadrao.ConsultarPrazoPadraoRequest requestData) {
            return base.Channel.ConsultarPrazoPadraoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoResponse AlterarTaxa(Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoRequest requestData) {
            return base.Channel.AlterarTaxa(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoResponse> AlterarTaxaAsync(Cielo.Sirius.Contracts.AlterarParcelaFaixaProduto.AlterarParcelaFaixaProdutoRequest requestData) {
            return base.Channel.AlterarTaxaAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaResponse SolicitarNegociacaoTaxaProdutoComercial(Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaRequest requestData) {
            return base.Channel.SolicitarNegociacaoTaxaProdutoComercial(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaResponse> SolicitarNegociacaoTaxaProdutoComercialAsync(Cielo.Sirius.Contracts.SolicitarNegociacaoTaxa.SolicitarNegociacaoTaxaRequest requestData) {
            return base.Channel.SolicitarNegociacaoTaxaProdutoComercialAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionResponse GetDiscountRateRestriction(Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionRequest requestData) {
            return base.Channel.GetDiscountRateRestriction(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionResponse> GetDiscountRateRestrictionAsync(Cielo.Sirius.Contracts.GetDiscountRateRestriction.GetDiscountRateRestrictionRequest requestData) {
            return base.Channel.GetDiscountRateRestrictionAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelResponse ManterPrazoFlexivel(Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelRequest requestData) {
            return base.Channel.ManterPrazoFlexivel(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelResponse> ManterPrazoFlexivelAsync(Cielo.Sirius.Contracts.HabilitarPrazoFlexivel.HabilitarPrazoFlexivelRequest requestData) {
            return base.Channel.ManterPrazoFlexivelAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaResponse HabilitarDesabilitarVendaDigitada(Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaRequest requestData) {
            return base.Channel.HabilitarDesabilitarVendaDigitada(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaResponse> HabilitarDesabilitarVendaDigitadaAsync(Cielo.Sirius.Contracts.HabilitarDesabilitarVendaDigitada.HabilitarDesabilitarVendaDigitadaRequest requestData) {
            return base.Channel.HabilitarDesabilitarVendaDigitadaAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoResponse SolicitarExclusaoProduto(Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoRequest requestData) {
            return base.Channel.SolicitarExclusaoProduto(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoResponse> SolicitarExclusaoProdutoAsync(Cielo.Sirius.Contracts.SolicitarExclusaoProduto.SolicitarExclusaoProdutoRequest requestData) {
            return base.Channel.SolicitarExclusaoProdutoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteResponse ConsultarServicoHabilitadoCliente(Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarServicoHabilitadoCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteResponse> ConsultarServicoHabilitadoClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoHabilitadoCliente.ConsultarServicoHabilitadoClienteRequest requestData) {
            return base.Channel.ConsultarServicoHabilitadoClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteResponse ConsultarDetalheProdutoMultivanContratadoCliente(Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoMultivanContratadoCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteResponse> ConsultarDetalheProdutoMultivanContratadoClienteAsync(Cielo.Sirius.Contracts.ConsultarDetalheProdutoMultivanContratadoCliente.ConsultarDetalheProdutoMultivanContratadoClienteRequest requestData) {
            return base.Channel.ConsultarDetalheProdutoMultivanContratadoClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraResponse SolicitaAnaliseAlvara(Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraRequest requestData) {
            return base.Channel.SolicitaAnaliseAlvara(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraResponse> SolicitaAnaliseAlvaraAsync(Cielo.Sirius.Contracts.SolicitaAnaliseAlvara.SolicitaAnaliseAlvaraRequest requestData) {
            return base.Channel.SolicitaAnaliseAlvaraAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoResponse HabilitarProduto(Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoRequest requestData) {
            return base.Channel.HabilitarProduto(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoResponse> HabilitarProdutoAsync(Cielo.Sirius.Contracts.HabilitarProduto.HabilitarProdutoRequest requestData) {
            return base.Channel.HabilitarProdutoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteResponse ConsultarServicoElegivelCliente(Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarServicoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteResponse> ConsultarServicoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoElegivelCliente.ConsultarServicoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarServicoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteResponse ConsultarServicoNaoElegivelCliente(Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarServicoNaoElegivelCliente(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteResponse> ConsultarServicoNaoElegivelClienteAsync(Cielo.Sirius.Contracts.ConsultarServicoNaoElegivelCliente.ConsultarServicoNaoElegivelClienteRequest requestData) {
            return base.Channel.ConsultarServicoNaoElegivelClienteAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaResponse ValidarPermissaoVendaDigitiada(Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaRequest requestData) {
            return base.Channel.ValidarPermissaoVendaDigitiada(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaResponse> ValidarPermissaoVendaDigitiadaAsync(Cielo.Sirius.Contracts.ValidarPermissaoVendaDigitada.ValidarPermissaoVendaDigitadaRequest requestData) {
            return base.Channel.ValidarPermissaoVendaDigitiadaAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoResponse HabilitarServico(Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoRequest requestData) {
            return base.Channel.HabilitarServico(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoResponse> HabilitarServicoAsync(Cielo.Sirius.Contracts.HabilitarServico.HabilitarServicoRequest requestData) {
            return base.Channel.HabilitarServicoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoResponse DesabilitarServico(Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoRequest requestData) {
            return base.Channel.DesabilitarServico(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoResponse> DesabilitarServicoAsync(Cielo.Sirius.Contracts.DesabilitarServico.DesabilitarServicoRequest requestData) {
            return base.Channel.DesabilitarServicoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoResponse DesabilitarProduto(Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoRequest requestData) {
            return base.Channel.DesabilitarProduto(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoResponse> DesabilitarProdutoAsync(Cielo.Sirius.Contracts.DesabilitarProduto.DesabilitarProdutoRequest requestData) {
            return base.Channel.DesabilitarProdutoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelResponse ConsultarPrazosTaxasPrazoFlexivel(Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelRequest requestData) {
            return base.Channel.ConsultarPrazosTaxasPrazoFlexivel(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelResponse> ConsultarPrazosTaxasPrazoFlexivelAsync(Cielo.Sirius.Contracts.ConsultarPrazosTaxasPrazoFlexivel.ConsultarPrazosTaxasPrazoFlexivelRequest requestData) {
            return base.Channel.ConsultarPrazosTaxasPrazoFlexivelAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelResponse ConsultarProdutosPrazoFlexivel(Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelRequest requestData) {
            return base.Channel.ConsultarProdutosPrazoFlexivel(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelResponse> ConsultarProdutosPrazoFlexivelAsync(Cielo.Sirius.Contracts.ConsultarProdutosPrazoFlexivel.ConsultarProdutosPrazoFlexivelRequest requestData) {
            return base.Channel.ConsultarProdutosPrazoFlexivelAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonResponse GetRequestReason(Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonRequest requestData) {
            return base.Channel.GetRequestReason(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonResponse> GetRequestReasonAsync(Cielo.Sirius.Contracts.GetRequestReason.GetRequestReasonRequest requestData) {
            return base.Channel.GetRequestReasonAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoResponse AlterarProdutoCreditoParceladoSegmentado(Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoRequest requestData) {
            return base.Channel.AlterarProdutoCreditoParceladoSegmentado(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoResponse> AlterarProdutoCreditoParceladoSegmentadoAsync(Cielo.Sirius.Contracts.AlterarProdutoCreditoParceladoSegmentado.AlterarProdutoCreditoParceladoSegmentadoRequest requestData) {
            return base.Channel.AlterarProdutoCreditoParceladoSegmentadoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaResponse AlterarProdutoAVista(Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaRequest requestData) {
            return base.Channel.AlterarProdutoAVista(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaResponse> AlterarProdutoAVistaAsync(Cielo.Sirius.Contracts.AlterarProdutoAVista.AlterarProdutoAVistaRequest requestData) {
            return base.Channel.AlterarProdutoAVistaAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoResponse CalcularAlcadaFaixasParceladoSegmentado(Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoRequest requestData) {
            return base.Channel.CalcularAlcadaFaixasParceladoSegmentado(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoResponse> CalcularAlcadaFaixasParceladoSegmentadoAsync(Cielo.Sirius.Contracts.CalcularAlcadaFaixasParceladoSegmentado.CalcularAlcadaFaixasParceladoSegmentadoRequest requestData) {
            return base.Channel.CalcularAlcadaFaixasParceladoSegmentadoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoResponse AlterarProdutoCreditoParcelado(Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoRequest requestData) {
            return base.Channel.AlterarProdutoCreditoParcelado(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoResponse> AlterarProdutoCreditoParceladoAsync(Cielo.Sirius.Contracts.AlterarProdutoCreditoParcelado.AlterarProdutoCreditoParceladoRequest requestData) {
            return base.Channel.AlterarProdutoCreditoParceladoAsync(requestData);
        }
        
        public Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoResponse ConsultarDadosNegociacao(Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoRequest requestData) {
            return base.Channel.ConsultarDadosNegociacao(requestData);
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoResponse> ConsultarDadosNegociacaoAsync(Cielo.Sirius.Contracts.ConsultarDadosNegociacao.ConsultarDadosNegociacaoRequest requestData) {
            return base.Channel.ConsultarDadosNegociacaoAsync(requestData);
        }
    }
}
