//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cielo.Sirius.DAO.Products.FaturamentoService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/canalrelacionamento/atendimentoassistido/v1")]
    public partial class SolicitacaoCentralAtendimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private string codigoSolicitacaoField;
        
        private System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacaoField;
        
        private bool dataPrevistaConclusaoSolicitacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
                this.RaisePropertyChanged("codigoClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string codigoSolicitacao {
            get {
                return this.codigoSolicitacaoField;
            }
            set {
                this.codigoSolicitacaoField = value;
                this.RaisePropertyChanged("codigoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacao {
            get {
                return this.dataPrevistaConclusaoSolicitacaoField;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoField = value;
                this.RaisePropertyChanged("dataPrevistaConclusaoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPrevistaConclusaoSolicitacaoSpecified {
            get {
                return this.dataPrevistaConclusaoSolicitacaoFieldSpecified;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoFieldSpecified = value;
                this.RaisePropertyChanged("dataPrevistaConclusaoSolicitacaoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", ConfigurationName="FaturamentoService.Servico")]
    internal interface Servico {
        
        // CODEGEN: Generating message contract since the operation solicitarNegociacaoTaxaProdutoComercial is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1/solicitarNegociac" +
            "aoTaxaProdutoComercial", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.FaturamentoService.Fault), Action="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1/solicitarNegociac" +
            "aoTaxaProdutoComercial", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialResponse solicitarNegociacaoTaxaProdutoComercial(Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1")]
    public partial class solicitarNegociacaoTaxaProdutoComercialRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protocoloField;
        
        private System.Nullable<long> codigoClienteField;
        
        private string codigoProdutoField;
        
        private string nomeContatoField;
        
        private System.Nullable<decimal> percentualTaxaPropostaConcorrenteField;
        
        private string celularContatoField;
        
        private string telefoneContatoField;
        
        private string codigoRacfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string codigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
                this.RaisePropertyChanged("codigoProduto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string nomeContato {
            get {
                return this.nomeContatoField;
            }
            set {
                this.nomeContatoField = value;
                this.RaisePropertyChanged("nomeContato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> percentualTaxaPropostaConcorrente {
            get {
                return this.percentualTaxaPropostaConcorrenteField;
            }
            set {
                this.percentualTaxaPropostaConcorrenteField = value;
                this.RaisePropertyChanged("percentualTaxaPropostaConcorrente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string celularContato {
            get {
                return this.celularContatoField;
            }
            set {
                this.celularContatoField = value;
                this.RaisePropertyChanged("celularContato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string telefoneContato {
            get {
                return this.telefoneContatoField;
            }
            set {
                this.telefoneContatoField = value;
                this.RaisePropertyChanged("telefoneContato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string codigoRacf {
            get {
                return this.codigoRacfField;
            }
            set {
                this.codigoRacfField = value;
                this.RaisePropertyChanged("codigoRacf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class solicitarNegociacaoTaxaProdutoComercialRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.FaturamentoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest solicitarNegociacaoTaxaProdutoComercialRequest;
        
        public solicitarNegociacaoTaxaProdutoComercialRequest1() {
        }
        
        public solicitarNegociacaoTaxaProdutoComercialRequest1(Cielo.Sirius.DAO.Products.FaturamentoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest solicitarNegociacaoTaxaProdutoComercialRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.solicitarNegociacaoTaxaProdutoComercialRequest = solicitarNegociacaoTaxaProdutoComercialRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarNegociacaoTaxaProdutoComercialResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", IsWrapped=true)]
    internal partial class solicitarNegociacaoTaxaProdutoComercialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=1)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=2)]
        public string statusRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=3)]
        public string sistemaLegado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/faturamento/faturamento/v1", Order=4)]
        public Cielo.Sirius.DAO.Products.FaturamentoService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento;
        
        public solicitarNegociacaoTaxaProdutoComercialResponse() {
        }
        
        public solicitarNegociacaoTaxaProdutoComercialResponse(string codigoRetorno, string descricaoRetornoMensagem, string statusRetorno, string sistemaLegado, Cielo.Sirius.DAO.Products.FaturamentoService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.statusRetorno = statusRetorno;
            this.sistemaLegado = sistemaLegado;
            this.solicitacaoCentralAtendimento = solicitacaoCentralAtendimento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ServicoChannel : Cielo.Sirius.DAO.Products.FaturamentoService.Servico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ServicoClient : System.ServiceModel.ClientBase<Cielo.Sirius.DAO.Products.FaturamentoService.Servico>, Cielo.Sirius.DAO.Products.FaturamentoService.Servico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialResponse Cielo.Sirius.DAO.Products.FaturamentoService.Servico.solicitarNegociacaoTaxaProdutoComercial(Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest1 request) {
            return base.Channel.solicitarNegociacaoTaxaProdutoComercial(request);
        }
        
        public string solicitarNegociacaoTaxaProdutoComercial(Cielo.Sirius.DAO.Products.FaturamentoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest solicitarNegociacaoTaxaProdutoComercialRequest, out string descricaoRetornoMensagem, out string statusRetorno, out string sistemaLegado, out Cielo.Sirius.DAO.Products.FaturamentoService.SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest1 inValue = new Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.solicitarNegociacaoTaxaProdutoComercialRequest = solicitarNegociacaoTaxaProdutoComercialRequest;
            Cielo.Sirius.DAO.Products.FaturamentoService.solicitarNegociacaoTaxaProdutoComercialResponse retVal = ((Cielo.Sirius.DAO.Products.FaturamentoService.Servico)(this)).solicitarNegociacaoTaxaProdutoComercial(inValue);
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            statusRetorno = retVal.statusRetorno;
            sistemaLegado = retVal.sistemaLegado;
            solicitacaoCentralAtendimento = retVal.solicitacaoCentralAtendimento;
            return retVal.codigoRetorno;
        }
    }
}
