//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Cielo.Sirius.DAO.Products.WR.Servico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoSOAP", Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Servico1))]
    public partial class Servico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private CieloSoapHeaderType cieloSoapHeaderField;
        
        private System.Threading.SendOrPostCallback consultarServicoHabilitadoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarServicoElegivelClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarServicoNaoElegivelClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback habilitarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback desabilitarServicoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servico() {
            this.Url = global::Cielo.Sirius.DAO.Products.Properties.Settings.Default.Cielo_Sirius_DAO_Products_WR_Servico_Servico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public CieloSoapHeaderType cieloSoapHeader {
            get {
                return this.cieloSoapHeaderField;
            }
            set {
                this.cieloSoapHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarServicoHabilitadoClienteCompletedEventHandler consultarServicoHabilitadoClienteCompleted;
        
        /// <remarks/>
        public event consultarServicoElegivelClienteCompletedEventHandler consultarServicoElegivelClienteCompleted;
        
        /// <remarks/>
        public event consultarServicoNaoElegivelClienteCompletedEventHandler consultarServicoNaoElegivelClienteCompleted;
        
        /// <remarks/>
        public event habilitarServicoCompletedEventHandler habilitarServicoCompleted;
        
        /// <remarks/>
        public event desabilitarServicoCompletedEventHandler desabilitarServicoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoHabilitad" +
            "oCliente", RequestElementName="consultarServicoHabilitadoClienteRequest", RequestNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ResponseNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("servicos")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("dadosServico")]
        public ServicoType[] consultarServicoHabilitadoCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao, out long numeroTotalRegistros, out System.DateTime dataUltimaTransacao, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool dataUltimaTransacaoSpecified, out bool indicadorVendaUltimoMes, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool indicadorVendaUltimoMesSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] out string codigoRetorno, out string descricaoRetornoMensagem) {
            object[] results = this.Invoke("consultarServicoHabilitadoCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            numeroTotalRegistros = ((long)(results[3]));
            dataUltimaTransacao = ((System.DateTime)(results[4]));
            dataUltimaTransacaoSpecified = ((bool)(results[5]));
            indicadorVendaUltimoMes = ((bool)(results[6]));
            indicadorVendaUltimoMesSpecified = ((bool)(results[7]));
            codigoRetorno = ((string)(results[8]));
            descricaoRetornoMensagem = ((string)(results[9]));
            return ((ServicoType[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarServicoHabilitadoClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao) {
            this.consultarServicoHabilitadoClienteAsync(codigoCliente, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarServicoHabilitadoClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarServicoHabilitadoClienteOperationCompleted == null)) {
                this.consultarServicoHabilitadoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarServicoHabilitadoClienteOperationCompleted);
            }
            this.InvokeAsync("consultarServicoHabilitadoCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao}, this.consultarServicoHabilitadoClienteOperationCompleted, userState);
        }
        
        private void OnconsultarServicoHabilitadoClienteOperationCompleted(object arg) {
            if ((this.consultarServicoHabilitadoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarServicoHabilitadoClienteCompleted(this, new consultarServicoHabilitadoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoElegivelC" +
            "liente", RequestElementName="consultarServicoElegivelClienteRequest", RequestNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ResponseNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("servicos")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("dadosServico")]
        public ServicoType[] consultarServicoElegivelCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao, out long numeroTotalRegistros, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] out string codigoRetorno, out string descricaoRetornoMensagem) {
            object[] results = this.Invoke("consultarServicoElegivelCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            numeroTotalRegistros = ((long)(results[3]));
            codigoRetorno = ((string)(results[4]));
            descricaoRetornoMensagem = ((string)(results[5]));
            return ((ServicoType[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarServicoElegivelClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao) {
            this.consultarServicoElegivelClienteAsync(codigoCliente, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarServicoElegivelClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarServicoElegivelClienteOperationCompleted == null)) {
                this.consultarServicoElegivelClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarServicoElegivelClienteOperationCompleted);
            }
            this.InvokeAsync("consultarServicoElegivelCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao}, this.consultarServicoElegivelClienteOperationCompleted, userState);
        }
        
        private void OnconsultarServicoElegivelClienteOperationCompleted(object arg) {
            if ((this.consultarServicoElegivelClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarServicoElegivelClienteCompleted(this, new consultarServicoElegivelClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoNaoElegiv" +
            "elCliente", RequestElementName="consultarServicoNaoElegivelClienteRequest", RequestNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ResponseNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("servicos")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("dadosServico")]
        public ServicoType[] consultarServicoNaoElegivelCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao, out long numeroTotalRegistros, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] out string codigoRetorno, out string descricaoRetornoMensagem) {
            object[] results = this.Invoke("consultarServicoNaoElegivelCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            numeroTotalRegistros = ((long)(results[3]));
            codigoRetorno = ((string)(results[4]));
            descricaoRetornoMensagem = ((string)(results[5]));
            return ((ServicoType[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarServicoNaoElegivelClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao) {
            this.consultarServicoNaoElegivelClienteAsync(codigoCliente, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarServicoNaoElegivelClienteAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarServicoNaoElegivelClienteOperationCompleted == null)) {
                this.consultarServicoNaoElegivelClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarServicoNaoElegivelClienteOperationCompleted);
            }
            this.InvokeAsync("consultarServicoNaoElegivelCliente", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao}, this.consultarServicoNaoElegivelClienteOperationCompleted, userState);
        }
        
        private void OnconsultarServicoNaoElegivelClienteOperationCompleted(object arg) {
            if ((this.consultarServicoNaoElegivelClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarServicoNaoElegivelClienteCompleted(this, new consultarServicoNaoElegivelClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.cielo.com.br/cadastro/servico/servico/v1/habilitarServico", RequestElementName="habilitarServicoRequest", RequestNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ResponseNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoRetorno", DataType="integer")]
        public string habilitarServico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)] string codigoServico, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string protocolo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string origem, out string descricaoRetornoMensagem, out string statusRetorno, out string sistemaLegado, out SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            object[] results = this.Invoke("habilitarServico", new object[] {
                        codigoCliente,
                        codigoServico,
                        protocolo,
                        origem});
            descricaoRetornoMensagem = ((string)(results[1]));
            statusRetorno = ((string)(results[2]));
            sistemaLegado = ((string)(results[3]));
            solicitacaoCentralAtendimento = ((SolicitacaoCentralAtendimento)(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void habilitarServicoAsync(System.Nullable<long> codigoCliente, string codigoServico, string protocolo, string origem) {
            this.habilitarServicoAsync(codigoCliente, codigoServico, protocolo, origem, null);
        }
        
        /// <remarks/>
        public void habilitarServicoAsync(System.Nullable<long> codigoCliente, string codigoServico, string protocolo, string origem, object userState) {
            if ((this.habilitarServicoOperationCompleted == null)) {
                this.habilitarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhabilitarServicoOperationCompleted);
            }
            this.InvokeAsync("habilitarServico", new object[] {
                        codigoCliente,
                        codigoServico,
                        protocolo,
                        origem}, this.habilitarServicoOperationCompleted, userState);
        }
        
        private void OnhabilitarServicoOperationCompleted(object arg) {
            if ((this.habilitarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.habilitarServicoCompleted(this, new habilitarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.cielo.com.br/cadastro/servico/servico/v1/desabilitarServico", RequestElementName="desabilitarServicoRequest", RequestNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ResponseNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoRetorno", DataType="integer")]
        public string desabilitarServico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)] string codigoServico, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string protocolo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string origem, out string descricaoRetornoMensagem, out string statusRetorno, out string sistemaLegado, out SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            object[] results = this.Invoke("desabilitarServico", new object[] {
                        codigoCliente,
                        codigoServico,
                        protocolo,
                        origem});
            descricaoRetornoMensagem = ((string)(results[1]));
            statusRetorno = ((string)(results[2]));
            sistemaLegado = ((string)(results[3]));
            solicitacaoCentralAtendimento = ((SolicitacaoCentralAtendimento)(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void desabilitarServicoAsync(System.Nullable<long> codigoCliente, string codigoServico, string protocolo, string origem) {
            this.desabilitarServicoAsync(codigoCliente, codigoServico, protocolo, origem, null);
        }
        
        /// <remarks/>
        public void desabilitarServicoAsync(System.Nullable<long> codigoCliente, string codigoServico, string protocolo, string origem, object userState) {
            if ((this.desabilitarServicoOperationCompleted == null)) {
                this.desabilitarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesabilitarServicoOperationCompleted);
            }
            this.InvokeAsync("desabilitarServico", new object[] {
                        codigoCliente,
                        codigoServico,
                        protocolo,
                        origem}, this.desabilitarServicoOperationCompleted, userState);
        }
        
        private void OndesabilitarServicoOperationCompleted(object arg) {
            if ((this.desabilitarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desabilitarServicoCompleted(this, new desabilitarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    [System.Xml.Serialization.XmlRootAttribute("cieloSoapHeader", Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1", IsNullable=false)]
    public partial class CieloSoapHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/canalrelacionamento/atendimentoassistido/v1")]
    public partial class SolicitacaoCentralAtendimento {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private string codigoSolicitacaoField;
        
        private System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacaoField;
        
        private bool dataPrevistaConclusaoSolicitacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string codigoSolicitacao {
            get {
                return this.codigoSolicitacaoField;
            }
            set {
                this.codigoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacao {
            get {
                return this.dataPrevistaConclusaoSolicitacaoField;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPrevistaConclusaoSolicitacaoSpecified {
            get {
                return this.dataPrevistaConclusaoSolicitacaoFieldSpecified;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicoType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Servico", Namespace="http://canonico.cielo.com.br/cadastro/v1")]
    public partial class Servico1 {
        
        private string codigoServicoField;
        
        private string nomeServicoField;
        
        private string descricaoServicoField;
        
        private System.Nullable<System.DateTime> dataHabilitacaoServicoField;
        
        private bool dataHabilitacaoServicoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string codigoServico {
            get {
                return this.codigoServicoField;
            }
            set {
                this.codigoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomeServico {
            get {
                return this.nomeServicoField;
            }
            set {
                this.nomeServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricaoServico {
            get {
                return this.descricaoServicoField;
            }
            set {
                this.descricaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataHabilitacaoServico {
            get {
                return this.dataHabilitacaoServicoField;
            }
            set {
                this.dataHabilitacaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataHabilitacaoServicoSpecified {
            get {
                return this.dataHabilitacaoServicoFieldSpecified;
            }
            set {
                this.dataHabilitacaoServicoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class ServicoType : Servico1 {
        
        private string vantagemField;
        
        /// <remarks/>
        public string vantagem {
            get {
                return this.vantagemField;
            }
            set {
                this.vantagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarServicoHabilitadoClienteCompletedEventHandler(object sender, consultarServicoHabilitadoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarServicoHabilitadoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarServicoHabilitadoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicoType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicoType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public long numeroTotalRegistros {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public System.DateTime dataUltimaTransacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public bool dataUltimaTransacaoSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public bool indicadorVendaUltimoMes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public bool indicadorVendaUltimoMesSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public string codigoRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarServicoElegivelClienteCompletedEventHandler(object sender, consultarServicoElegivelClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarServicoElegivelClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarServicoElegivelClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicoType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicoType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public long numeroTotalRegistros {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string codigoRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarServicoNaoElegivelClienteCompletedEventHandler(object sender, consultarServicoNaoElegivelClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarServicoNaoElegivelClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarServicoNaoElegivelClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicoType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicoType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public long numeroTotalRegistros {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string codigoRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void habilitarServicoCompletedEventHandler(object sender, habilitarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class habilitarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal habilitarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string statusRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string sistemaLegado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public SolicitacaoCentralAtendimento solicitacaoCentralAtendimento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SolicitacaoCentralAtendimento)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void desabilitarServicoCompletedEventHandler(object sender, desabilitarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desabilitarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desabilitarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string statusRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string sistemaLegado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public SolicitacaoCentralAtendimento solicitacaoCentralAtendimento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SolicitacaoCentralAtendimento)(this.results[4]));
            }
        }
    }
}

#pragma warning restore 1591