//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cielo.Sirius.DAO.Products.NegociacaoService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cielo.com.br/temporario/v1")]
    public partial class listaDemandaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroReferenciaField;
        
        private bool numeroReferenciaFieldSpecified;
        
        private long tipoDemandaField;
        
        private bool tipoDemandaFieldSpecified;
        
        private string descricaoItemDemandaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroReferencia {
            get {
                return this.numeroReferenciaField;
            }
            set {
                this.numeroReferenciaField = value;
                this.RaisePropertyChanged("numeroReferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroReferenciaSpecified {
            get {
                return this.numeroReferenciaFieldSpecified;
            }
            set {
                this.numeroReferenciaFieldSpecified = value;
                this.RaisePropertyChanged("numeroReferenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long tipoDemanda {
            get {
                return this.tipoDemandaField;
            }
            set {
                this.tipoDemandaField = value;
                this.RaisePropertyChanged("tipoDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDemandaSpecified {
            get {
                return this.tipoDemandaFieldSpecified;
            }
            set {
                this.tipoDemandaFieldSpecified = value;
                this.RaisePropertyChanged("tipoDemandaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descricaoItemDemanda {
            get {
                return this.descricaoItemDemandaField;
            }
            set {
                this.descricaoItemDemandaField = value;
                this.RaisePropertyChanged("descricaoItemDemanda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cielo.com.br/temporario/v1", ConfigurationName="NegociacaoService.TemporarioServicePortType")]
    public interface TemporarioServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cielo.com.br/temporario/v1/TemporarioServicePortType/consultarElegibilidad" +
            "eNegociacaoComercialRequest", ReplyAction="http://cielo.com.br/temporario/v1/TemporarioServicePortType/consultarElegibilidad" +
            "eNegociacaoComercialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.NegociacaoService.Fault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse consultarElegibilidadeNegociacaoComercial(Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://cielo.com.br/temporario/v1/TemporarioServicePortType/consultarElegibilidad" +
            "eNegociacaoComercialRequest", ReplyAction="http://cielo.com.br/temporario/v1/TemporarioServicePortType/consultarElegibilidad" +
            "eNegociacaoComercialResponse")]
        System.Threading.Tasks.Task<Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse> consultarElegibilidadeNegociacaoComercialAsync(Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarElegibilidadeNegociacaoComercialRequest", WrapperNamespace="http://cielo.com.br/temporario/v1", IsWrapped=true)]
    public partial class consultarElegibilidadeNegociacaoComercialRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.NegociacaoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cielo.com.br/temporario/v1", Order=0)]
        public long codigoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cielo.com.br/temporario/v1", Order=1)]
        public long codigoTipoDemanda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cielo.com.br/temporario/v1", Order=2)]
        public long codigoSubTipoDemanda;
        
        public consultarElegibilidadeNegociacaoComercialRequest() {
        }
        
        public consultarElegibilidadeNegociacaoComercialRequest(Cielo.Sirius.DAO.Products.NegociacaoService.CieloSoapHeaderType cieloSoapHeader, long codigoCliente, long codigoTipoDemanda, long codigoSubTipoDemanda) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.codigoCliente = codigoCliente;
            this.codigoTipoDemanda = codigoTipoDemanda;
            this.codigoSubTipoDemanda = codigoSubTipoDemanda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarElegibilidadeNegociacaoComercialResponse", WrapperNamespace="http://cielo.com.br/temporario/v1", IsWrapped=true)]
    public partial class consultarElegibilidadeNegociacaoComercialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cielo.com.br/temporario/v1", Order=0)]
        public bool indicadorElegibilidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cielo.com.br/temporario/v1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("listaDemanda")]
        public Cielo.Sirius.DAO.Products.NegociacaoService.listaDemandaType[] listaDemanda;
        
        public consultarElegibilidadeNegociacaoComercialResponse() {
        }
        
        public consultarElegibilidadeNegociacaoComercialResponse(bool indicadorElegibilidade, Cielo.Sirius.DAO.Products.NegociacaoService.listaDemandaType[] listaDemanda) {
            this.indicadorElegibilidade = indicadorElegibilidade;
            this.listaDemanda = listaDemanda;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TemporarioServicePortTypeChannel : Cielo.Sirius.DAO.Products.NegociacaoService.TemporarioServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemporarioServicePortTypeClient : System.ServiceModel.ClientBase<Cielo.Sirius.DAO.Products.NegociacaoService.TemporarioServicePortType>, Cielo.Sirius.DAO.Products.NegociacaoService.TemporarioServicePortType {
        
        public TemporarioServicePortTypeClient() {
        }
        
        public TemporarioServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemporarioServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemporarioServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemporarioServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse Cielo.Sirius.DAO.Products.NegociacaoService.TemporarioServicePortType.consultarElegibilidadeNegociacaoComercial(Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest request) {
            return base.Channel.consultarElegibilidadeNegociacaoComercial(request);
        }

        public Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse consultarElegibilidadeNegociacaoComercial(Cielo.Sirius.DAO.Products.NegociacaoService.CieloSoapHeaderType cieloSoapHeader, long codigoCliente, long codigoTipoDemanda, long codigoSubTipoDemanda, out Cielo.Sirius.DAO.Products.NegociacaoService.listaDemandaType[] listaDemanda)
        {
            Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest inValue = new Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.codigoCliente = codigoCliente;
            inValue.codigoTipoDemanda = codigoTipoDemanda;
            inValue.codigoSubTipoDemanda = codigoSubTipoDemanda;
            Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse retVal = ((Cielo.Sirius.DAO.Products.NegociacaoService.TemporarioServicePortType)(this)).consultarElegibilidadeNegociacaoComercial(inValue);
            listaDemanda = retVal.listaDemanda;
            return retVal;
        }
        
        public System.Threading.Tasks.Task<Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialResponse> consultarElegibilidadeNegociacaoComercialAsync(Cielo.Sirius.DAO.Products.NegociacaoService.consultarElegibilidadeNegociacaoComercialRequest request) {
            return base.Channel.consultarElegibilidadeNegociacaoComercialAsync(request);
        }
    }
}
