//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cielo.Sirius.DAO.Products.ServicoService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/cadastro/v1")]
    public partial class Servico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoServicoField;
        
        private string nomeServicoField;
        
        private string descricaoServicoField;
        
        private System.Nullable<System.DateTime> dataHabilitacaoServicoField;
        
        private bool dataHabilitacaoServicoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string codigoServico {
            get {
                return this.codigoServicoField;
            }
            set {
                this.codigoServicoField = value;
                this.RaisePropertyChanged("codigoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nomeServico {
            get {
                return this.nomeServicoField;
            }
            set {
                this.nomeServicoField = value;
                this.RaisePropertyChanged("nomeServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string descricaoServico {
            get {
                return this.descricaoServicoField;
            }
            set {
                this.descricaoServicoField = value;
                this.RaisePropertyChanged("descricaoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dataHabilitacaoServico {
            get {
                return this.dataHabilitacaoServicoField;
            }
            set {
                this.dataHabilitacaoServicoField = value;
                this.RaisePropertyChanged("dataHabilitacaoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataHabilitacaoServicoSpecified {
            get {
                return this.dataHabilitacaoServicoFieldSpecified;
            }
            set {
                this.dataHabilitacaoServicoFieldSpecified = value;
                this.RaisePropertyChanged("dataHabilitacaoServicoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Servico", Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", ConfigurationName="ServicoService.Servico1")]
    internal interface Servico1 {
        
        // CODEGEN: Generating message contract since the operation consultarServicoHabilitadoCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoHabilitad" +
            "oCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.ServicoService.Fault), Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoHabilitad" +
            "oCliente", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteResponse consultarServicoHabilitadoCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation consultarServicoElegivelCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoElegivelC" +
            "liente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.ServicoService.Fault), Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoElegivelC" +
            "liente", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteResponse consultarServicoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation consultarServicoNaoElegivelCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoNaoElegiv" +
            "elCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.ServicoService.Fault), Action="http://service.cielo.com.br/cadastro/servico/servico/v1/consultarServicoNaoElegiv" +
            "elCliente", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteResponse consultarServicoNaoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation habilitarServico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/servico/servico/v1/habilitarServico", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.ServicoService.Fault), Action="http://service.cielo.com.br/cadastro/servico/servico/v1/habilitarServico", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoResponse habilitarServico(Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation desabilitarServico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/cadastro/servico/servico/v1/desabilitarServico", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cielo.Sirius.DAO.Products.ServicoService.Fault), Action="http://service.cielo.com.br/cadastro/servico/servico/v1/desabilitarServico", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoResponse desabilitarServico(Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class consultarServicoHabilitadoClienteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarServicoHabilitadoClienteRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest consultarServicoHabilitadoClienteRequest;
        
        public consultarServicoHabilitadoClienteRequest1() {
        }
        
        public consultarServicoHabilitadoClienteRequest1(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest consultarServicoHabilitadoClienteRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarServicoHabilitadoClienteRequest = consultarServicoHabilitadoClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarServicoHabilitadoClienteResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", IsWrapped=true)]
    internal partial class consultarServicoHabilitadoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dadosServico", Namespace="http://canonico.cielo.com.br/cadastro/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=1)]
        public long numeroTotalRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=2)]
        public System.DateTime dataUltimaTransacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=3)]
        public bool indicadorVendaUltimoMes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=4)]
        public string vantagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=6)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=7)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=8)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarServicoHabilitadoClienteResponse() {
        }
        
        public consultarServicoHabilitadoClienteResponse(Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos, long numeroTotalRegistros, System.DateTime dataUltimaTransacao, bool indicadorVendaUltimoMes, string vantagem, string codigoRetorno, string descricaoRetornoMensagem, string proximoRegistro, string chavePaginacao) {
            this.servicos = servicos;
            this.numeroTotalRegistros = numeroTotalRegistros;
            this.dataUltimaTransacao = dataUltimaTransacao;
            this.indicadorVendaUltimoMes = indicadorVendaUltimoMes;
            this.vantagem = vantagem;
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class consultarServicoElegivelClienteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarServicoElegivelClienteRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest consultarServicoElegivelClienteRequest;
        
        public consultarServicoElegivelClienteRequest1() {
        }
        
        public consultarServicoElegivelClienteRequest1(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest consultarServicoElegivelClienteRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarServicoElegivelClienteRequest = consultarServicoElegivelClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarServicoElegivelClienteResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", IsWrapped=true)]
    internal partial class consultarServicoElegivelClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dadosServico", Namespace="http://canonico.cielo.com.br/cadastro/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=1)]
        public long numeroTotalRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=2)]
        public string vantagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=4)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=5)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=6)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarServicoElegivelClienteResponse() {
        }
        
        public consultarServicoElegivelClienteResponse(Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos, long numeroTotalRegistros, string vantagem, string codigoRetorno, string descricaoRetornoMensagem, string proximoRegistro, string chavePaginacao) {
            this.servicos = servicos;
            this.numeroTotalRegistros = numeroTotalRegistros;
            this.vantagem = vantagem;
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class consultarServicoNaoElegivelClienteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class consultarServicoNaoElegivelClienteRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest consultarServicoNaoElegivelClienteRequest;
        
        public consultarServicoNaoElegivelClienteRequest1() {
        }
        
        public consultarServicoNaoElegivelClienteRequest1(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest consultarServicoNaoElegivelClienteRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarServicoNaoElegivelClienteRequest = consultarServicoNaoElegivelClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarServicoNaoElegivelClienteResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", IsWrapped=true)]
    internal partial class consultarServicoNaoElegivelClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dadosServico", Namespace="http://canonico.cielo.com.br/cadastro/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=1)]
        public long numeroTotalRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=2)]
        public string vantagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=4)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=5)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=6)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public consultarServicoNaoElegivelClienteResponse() {
        }
        
        public consultarServicoNaoElegivelClienteResponse(Cielo.Sirius.DAO.Products.ServicoService.Servico[] servicos, long numeroTotalRegistros, string vantagem, string codigoRetorno, string descricaoRetornoMensagem, string proximoRegistro, string chavePaginacao) {
            this.servicos = servicos;
            this.numeroTotalRegistros = numeroTotalRegistros;
            this.vantagem = vantagem;
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class habilitarServicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string codigoServicoField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string codigoServico {
            get {
                return this.codigoServicoField;
            }
            set {
                this.codigoServicoField = value;
                this.RaisePropertyChanged("codigoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class habilitarServicoRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest habilitarServicoRequest;
        
        public habilitarServicoRequest1() {
        }
        
        public habilitarServicoRequest1(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest habilitarServicoRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.habilitarServicoRequest = habilitarServicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="habilitarServicoResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", IsWrapped=true)]
    internal partial class habilitarServicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=1)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public habilitarServicoResponse() {
        }
        
        public habilitarServicoResponse(string codigoRetorno, string descricaoRetornoMensagem, string proximoRegistro, string chavePaginacao) {
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1")]
    public partial class desabilitarServicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoClienteField;
        
        private string codigoServicoField;
        
        private string proximoRegistroField;
        
        private string chavePaginacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string codigoServico {
            get {
                return this.codigoServicoField;
            }
            set {
                this.codigoServicoField = value;
                this.RaisePropertyChanged("codigoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro {
            get {
                return this.proximoRegistroField;
            }
            set {
                this.proximoRegistroField = value;
                this.RaisePropertyChanged("proximoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao {
            get {
                return this.chavePaginacaoField;
            }
            set {
                this.chavePaginacaoField = value;
                this.RaisePropertyChanged("chavePaginacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class desabilitarServicoRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        public Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest desabilitarServicoRequest;
        
        public desabilitarServicoRequest1() {
        }
        
        public desabilitarServicoRequest1(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest desabilitarServicoRequest) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.desabilitarServicoRequest = desabilitarServicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desabilitarServicoResponse", WrapperNamespace="http://service.cielo.com.br/cadastro/servico/servico/v1", IsWrapped=true)]
    internal partial class desabilitarServicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/cadastro/servico/servico/v1", Order=1)]
        public string descricaoRetornoMensagem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proximoRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://canonico.cielo.com.br/comum/v1", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chavePaginacao;
        
        public desabilitarServicoResponse() {
        }
        
        public desabilitarServicoResponse(string codigoRetorno, string descricaoRetornoMensagem, string proximoRegistro, string chavePaginacao) {
            this.codigoRetorno = codigoRetorno;
            this.descricaoRetornoMensagem = descricaoRetornoMensagem;
            this.proximoRegistro = proximoRegistro;
            this.chavePaginacao = chavePaginacao;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface Servico1Channel : Cielo.Sirius.DAO.Products.ServicoService.Servico1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class Servico1Client : System.ServiceModel.ClientBase<Cielo.Sirius.DAO.Products.ServicoService.Servico1>, Cielo.Sirius.DAO.Products.ServicoService.Servico1 {
        
        public Servico1Client() {
        }
        
        public Servico1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Servico1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteResponse Cielo.Sirius.DAO.Products.ServicoService.Servico1.consultarServicoHabilitadoCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest1 request) {
            return base.Channel.consultarServicoHabilitadoCliente(request);
        }
        
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] consultarServicoHabilitadoCliente(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest consultarServicoHabilitadoClienteRequest, out long numeroTotalRegistros, out System.DateTime dataUltimaTransacao, out bool indicadorVendaUltimoMes, out string vantagem, out string codigoRetorno, out string descricaoRetornoMensagem, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest1 inValue = new Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarServicoHabilitadoClienteRequest = consultarServicoHabilitadoClienteRequest;
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoHabilitadoClienteResponse retVal = ((Cielo.Sirius.DAO.Products.ServicoService.Servico1)(this)).consultarServicoHabilitadoCliente(inValue);
            numeroTotalRegistros = retVal.numeroTotalRegistros;
            dataUltimaTransacao = retVal.dataUltimaTransacao;
            indicadorVendaUltimoMes = retVal.indicadorVendaUltimoMes;
            vantagem = retVal.vantagem;
            codigoRetorno = retVal.codigoRetorno;
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.servicos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteResponse Cielo.Sirius.DAO.Products.ServicoService.Servico1.consultarServicoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest1 request) {
            return base.Channel.consultarServicoElegivelCliente(request);
        }
        
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] consultarServicoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest consultarServicoElegivelClienteRequest, out long numeroTotalRegistros, out string vantagem, out string codigoRetorno, out string descricaoRetornoMensagem, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest1 inValue = new Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarServicoElegivelClienteRequest = consultarServicoElegivelClienteRequest;
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoElegivelClienteResponse retVal = ((Cielo.Sirius.DAO.Products.ServicoService.Servico1)(this)).consultarServicoElegivelCliente(inValue);
            numeroTotalRegistros = retVal.numeroTotalRegistros;
            vantagem = retVal.vantagem;
            codigoRetorno = retVal.codigoRetorno;
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.servicos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteResponse Cielo.Sirius.DAO.Products.ServicoService.Servico1.consultarServicoNaoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest1 request) {
            return base.Channel.consultarServicoNaoElegivelCliente(request);
        }
        
        public Cielo.Sirius.DAO.Products.ServicoService.Servico[] consultarServicoNaoElegivelCliente(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest consultarServicoNaoElegivelClienteRequest, out long numeroTotalRegistros, out string vantagem, out string codigoRetorno, out string descricaoRetornoMensagem, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest1 inValue = new Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarServicoNaoElegivelClienteRequest = consultarServicoNaoElegivelClienteRequest;
            Cielo.Sirius.DAO.Products.ServicoService.consultarServicoNaoElegivelClienteResponse retVal = ((Cielo.Sirius.DAO.Products.ServicoService.Servico1)(this)).consultarServicoNaoElegivelCliente(inValue);
            numeroTotalRegistros = retVal.numeroTotalRegistros;
            vantagem = retVal.vantagem;
            codigoRetorno = retVal.codigoRetorno;
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.servicos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoResponse Cielo.Sirius.DAO.Products.ServicoService.Servico1.habilitarServico(Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest1 request) {
            return base.Channel.habilitarServico(request);
        }
        
        public string habilitarServico(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest habilitarServicoRequest, out string descricaoRetornoMensagem, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest1 inValue = new Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.habilitarServicoRequest = habilitarServicoRequest;
            Cielo.Sirius.DAO.Products.ServicoService.habilitarServicoResponse retVal = ((Cielo.Sirius.DAO.Products.ServicoService.Servico1)(this)).habilitarServico(inValue);
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.codigoRetorno;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoResponse Cielo.Sirius.DAO.Products.ServicoService.Servico1.desabilitarServico(Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest1 request) {
            return base.Channel.desabilitarServico(request);
        }
        
        public string desabilitarServico(Cielo.Sirius.DAO.Products.ServicoService.CieloSoapHeaderType cieloSoapHeader, Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest desabilitarServicoRequest, out string descricaoRetornoMensagem, out string proximoRegistro, out string chavePaginacao) {
            Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest1 inValue = new Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoRequest1();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.desabilitarServicoRequest = desabilitarServicoRequest;
            Cielo.Sirius.DAO.Products.ServicoService.desabilitarServicoResponse retVal = ((Cielo.Sirius.DAO.Products.ServicoService.Servico1)(this)).desabilitarServico(inValue);
            descricaoRetornoMensagem = retVal.descricaoRetornoMensagem;
            proximoRegistro = retVal.proximoRegistro;
            chavePaginacao = retVal.chavePaginacao;
            return retVal.codigoRetorno;
        }
    }
}
