//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Cielo.Sirius.DAO.Products.WR.Material {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaterialServiceSOAPBinding", Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class MaterialService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private CieloSoapHeaderType cieloSoapHeaderField;
        
        private System.Threading.SendOrPostCallback consultarHistoricoSolicitacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarSuprimentoElegivelOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarHistoricoConsumoOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarMaterialOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MaterialService() {
            this.Url = global::Cielo.Sirius.DAO.Products.Properties.Settings.Default.ServiceURL_Material;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public CieloSoapHeaderType cieloSoapHeader {
            get {
                return this.cieloSoapHeaderField;
            }
            set {
                this.cieloSoapHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarHistoricoSolicitacaoCompletedEventHandler consultarHistoricoSolicitacaoCompleted;
        
        /// <remarks/>
        public event consultarSuprimentoElegivelCompletedEventHandler consultarSuprimentoElegivelCompleted;
        
        /// <remarks/>
        public event consultarHistoricoConsumoCompletedEventHandler consultarHistoricoConsumoCompleted;
        
        /// <remarks/>
        public event solicitarMaterialCompletedEventHandler solicitarMaterialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="consultarHistoricoSolicitacaoRequest", RequestNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", ResponseNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("materialSolicitadoCliente")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("materialSolicitadoCliente", IsNullable=false)]
        public MaterialSolicitadoCliente[] consultarHistoricoSolicitacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao) {
            object[] results = this.Invoke("consultarHistoricoSolicitacao", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            return ((MaterialSolicitadoCliente[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarHistoricoSolicitacaoAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao) {
            this.consultarHistoricoSolicitacaoAsync(codigoCliente, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarHistoricoSolicitacaoAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarHistoricoSolicitacaoOperationCompleted == null)) {
                this.consultarHistoricoSolicitacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarHistoricoSolicitacaoOperationCompleted);
            }
            this.InvokeAsync("consultarHistoricoSolicitacao", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao}, this.consultarHistoricoSolicitacaoOperationCompleted, userState);
        }
        
        private void OnconsultarHistoricoSolicitacaoOperationCompleted(object arg) {
            if ((this.consultarHistoricoSolicitacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarHistoricoSolicitacaoCompleted(this, new consultarHistoricoSolicitacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="consultarSuprimentoElegivelRequest", RequestNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", ResponseNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("materiais")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("material", IsNullable=false)]
        public Material[] consultarSuprimentoElegivel([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao) {
            object[] results = this.Invoke("consultarSuprimentoElegivel", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            return ((Material[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarSuprimentoElegivelAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao) {
            this.consultarSuprimentoElegivelAsync(codigoCliente, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarSuprimentoElegivelAsync(System.Nullable<long> codigoCliente, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarSuprimentoElegivelOperationCompleted == null)) {
                this.consultarSuprimentoElegivelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarSuprimentoElegivelOperationCompleted);
            }
            this.InvokeAsync("consultarSuprimentoElegivel", new object[] {
                        codigoCliente,
                        proximoRegistro,
                        chavePaginacao}, this.consultarSuprimentoElegivelOperationCompleted, userState);
        }
        
        private void OnconsultarSuprimentoElegivelOperationCompleted(object arg) {
            if ((this.consultarSuprimentoElegivelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarSuprimentoElegivelCompleted(this, new consultarSuprimentoElegivelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="consultarHistoricoConsumoRequest", RequestNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", ResponseNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("material")]
        public Material consultarHistoricoConsumo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)] string codigoMaterial, [System.Xml.Serialization.XmlAttributeAttribute()] ref string proximoRegistro, [System.Xml.Serialization.XmlAttributeAttribute()] ref string chavePaginacao, [System.Xml.Serialization.XmlArrayItemAttribute("infoHistoricoConsumo", IsNullable=false)] out InfoHistoricoConsumoType[] dadosHistoricoConsumo) {
            object[] results = this.Invoke("consultarHistoricoConsumo", new object[] {
                        codigoCliente,
                        codigoMaterial,
                        proximoRegistro,
                        chavePaginacao});
            proximoRegistro = ((string)(results[1]));
            chavePaginacao = ((string)(results[2]));
            dadosHistoricoConsumo = ((InfoHistoricoConsumoType[])(results[3]));
            return ((Material)(results[0]));
        }
        
        /// <remarks/>
        public void consultarHistoricoConsumoAsync(System.Nullable<long> codigoCliente, string codigoMaterial, string proximoRegistro, string chavePaginacao) {
            this.consultarHistoricoConsumoAsync(codigoCliente, codigoMaterial, proximoRegistro, chavePaginacao, null);
        }
        
        /// <remarks/>
        public void consultarHistoricoConsumoAsync(System.Nullable<long> codigoCliente, string codigoMaterial, string proximoRegistro, string chavePaginacao, object userState) {
            if ((this.consultarHistoricoConsumoOperationCompleted == null)) {
                this.consultarHistoricoConsumoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarHistoricoConsumoOperationCompleted);
            }
            this.InvokeAsync("consultarHistoricoConsumo", new object[] {
                        codigoCliente,
                        codigoMaterial,
                        proximoRegistro,
                        chavePaginacao}, this.consultarHistoricoConsumoOperationCompleted, userState);
        }
        
        private void OnconsultarHistoricoConsumoOperationCompleted(object arg) {
            if ((this.consultarHistoricoConsumoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarHistoricoConsumoCompleted(this, new consultarHistoricoConsumoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cieloSoapHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="solicitarMaterialRequest", RequestNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", ResponseNamespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoRetorno", DataType="integer")]
        public string solicitarMaterial([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string protocolo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> codigoCliente, [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)] string codigoMaterial, [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)] string quantidadeMaterial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomeResponsavel, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomeContato, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string telefoneContato, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string justificativaSolicitacao, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string codigoRacf, out string descricaoRetornoMensagem, out string statusRetorno, out string sistemaLegado, out SolicitacaoCentralAtendimento solicitacaoCentralAtendimento) {
            object[] results = this.Invoke("solicitarMaterial", new object[] {
                        protocolo,
                        codigoCliente,
                        codigoMaterial,
                        quantidadeMaterial,
                        nomeResponsavel,
                        nomeContato,
                        telefoneContato,
                        justificativaSolicitacao,
                        codigoRacf});
            descricaoRetornoMensagem = ((string)(results[1]));
            statusRetorno = ((string)(results[2]));
            sistemaLegado = ((string)(results[3]));
            solicitacaoCentralAtendimento = ((SolicitacaoCentralAtendimento)(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarMaterialAsync(string protocolo, System.Nullable<long> codigoCliente, string codigoMaterial, string quantidadeMaterial, string nomeResponsavel, string nomeContato, string telefoneContato, string justificativaSolicitacao, string codigoRacf) {
            this.solicitarMaterialAsync(protocolo, codigoCliente, codigoMaterial, quantidadeMaterial, nomeResponsavel, nomeContato, telefoneContato, justificativaSolicitacao, codigoRacf, null);
        }
        
        /// <remarks/>
        public void solicitarMaterialAsync(string protocolo, System.Nullable<long> codigoCliente, string codigoMaterial, string quantidadeMaterial, string nomeResponsavel, string nomeContato, string telefoneContato, string justificativaSolicitacao, string codigoRacf, object userState) {
            if ((this.solicitarMaterialOperationCompleted == null)) {
                this.solicitarMaterialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarMaterialOperationCompleted);
            }
            this.InvokeAsync("solicitarMaterial", new object[] {
                        protocolo,
                        codigoCliente,
                        codigoMaterial,
                        quantidadeMaterial,
                        nomeResponsavel,
                        nomeContato,
                        telefoneContato,
                        justificativaSolicitacao,
                        codigoRacf}, this.solicitarMaterialOperationCompleted, userState);
        }
        
        private void OnsolicitarMaterialOperationCompleted(object arg) {
            if ((this.solicitarMaterialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarMaterialCompleted(this, new solicitarMaterialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    [System.Xml.Serialization.XmlRootAttribute("cieloSoapHeader", Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1", IsNullable=false)]
    public partial class CieloSoapHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/canalrelacionamento/atendimentoassistido/v1")]
    public partial class SolicitacaoCentralAtendimento {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private string codigoSolicitacaoField;
        
        private System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacaoField;
        
        private bool dataPrevistaConclusaoSolicitacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string codigoSolicitacao {
            get {
                return this.codigoSolicitacaoField;
            }
            set {
                this.codigoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> dataPrevistaConclusaoSolicitacao {
            get {
                return this.dataPrevistaConclusaoSolicitacaoField;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPrevistaConclusaoSolicitacaoSpecified {
            get {
                return this.dataPrevistaConclusaoSolicitacaoFieldSpecified;
            }
            set {
                this.dataPrevistaConclusaoSolicitacaoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/cadastro/solucaocaptura/material/v2/")]
    public partial class InfoHistoricoConsumoType {
        
        private string mesConsumoField;
        
        private string quantidadeSuprimentoField;
        
        /// <remarks/>
        public string mesConsumo {
            get {
                return this.mesConsumoField;
            }
            set {
                this.mesConsumoField = value;
            }
        }
        
        /// <remarks/>
        public string quantidadeSuprimento {
            get {
                return this.quantidadeSuprimentoField;
            }
            set {
                this.quantidadeSuprimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/operacao/logistica/v1")]
    public partial class Material {
        
        private string codigoMaterialField;
        
        private string descricaoMaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricaoMaterial {
            get {
                return this.descricaoMaterialField;
            }
            set {
                this.descricaoMaterialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/operacao/logistica/v1")]
    public partial class MaterialSolicitadoCliente {
        
        private System.Nullable<long> codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private Material dadosMaterialField;
        
        private string quantidadeMaterialField;
        
        private string quantidadeDiaPrazoEntregaField;
        
        private System.Nullable<System.DateTime> dataSolicitacaoField;
        
        private bool dataSolicitacaoFieldSpecified;
        
        private string codigoUsuarioOperadorField;
        
        private string nomeTipoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Material dadosMaterial {
            get {
                return this.dadosMaterialField;
            }
            set {
                this.dadosMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string quantidadeMaterial {
            get {
                return this.quantidadeMaterialField;
            }
            set {
                this.quantidadeMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string quantidadeDiaPrazoEntrega {
            get {
                return this.quantidadeDiaPrazoEntregaField;
            }
            set {
                this.quantidadeDiaPrazoEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> dataSolicitacao {
            get {
                return this.dataSolicitacaoField;
            }
            set {
                this.dataSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSolicitacaoSpecified {
            get {
                return this.dataSolicitacaoFieldSpecified;
            }
            set {
                this.dataSolicitacaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoUsuarioOperador {
            get {
                return this.codigoUsuarioOperadorField;
            }
            set {
                this.codigoUsuarioOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomeTipoSolicitacao {
            get {
                return this.nomeTipoSolicitacaoField;
            }
            set {
                this.nomeTipoSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarHistoricoSolicitacaoCompletedEventHandler(object sender, consultarHistoricoSolicitacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarHistoricoSolicitacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarHistoricoSolicitacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MaterialSolicitadoCliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MaterialSolicitadoCliente[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarSuprimentoElegivelCompletedEventHandler(object sender, consultarSuprimentoElegivelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarSuprimentoElegivelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarSuprimentoElegivelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Material[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Material[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultarHistoricoConsumoCompletedEventHandler(object sender, consultarHistoricoConsumoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarHistoricoConsumoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarHistoricoConsumoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Material Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Material)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string proximoRegistro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string chavePaginacao {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public InfoHistoricoConsumoType[] dadosHistoricoConsumo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoHistoricoConsumoType[])(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void solicitarMaterialCompletedEventHandler(object sender, solicitarMaterialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarMaterialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarMaterialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string descricaoRetornoMensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string statusRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string sistemaLegado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public SolicitacaoCentralAtendimento solicitacaoCentralAtendimento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SolicitacaoCentralAtendimento)(this.results[4]));
            }
        }
    }
}

#pragma warning restore 1591